### ISSUE TITLE
DodgeGame on Tixte redirects to login even when logged in

### ISSUE THREAD

**Issue by colecci** [tixte/version-2.0#4]
Going to [https://tixte.com/games/dodge](url) redirects you to the login even when you just logged in. This issue should be fixed soon.

**Comment by michaelfm1211** [comment]
I have fixed this bug very trivially. If this happens ever again in any game just be aware that you can run the command
```bash
diff [name of working file] [problematic file]
```
and replace any verification code in the problematic file with the verification code in the working file
